
# file generated by /unihan/Makefile
with open('variants/kSimplifiedVariant.txt', 'r') as f:
    unihan = {line.split('\t')[0]: line.split('\t')[1] for line in f.read().strip().split('\n')}

with open('variants/TSCharacters.txt', 'r') as f:
    opencc = {line.split('\t')[0]: line.split('\t')[1] for line in f.read().strip().split('\n')}

unihan_only = [a for a in unihan.keys() if a not in opencc]
opencc_only = [a for a in opencc.keys() if a not in unihan]
print('Strict TC -> SC equivalences:\n\tUniHan: {}\n\tOpenCC: {}\n'.format(len(unihan), len(opencc)))
print('Specific equivalences:\n\tUniHan only: {}\n\tOpenCC only :{}\n'.format(len(unihan_only), len(opencc_only)))

similar_equivalents = [a for a in unihan.keys() if a in opencc and unihan[a] == opencc[a]]
differing_equivalents = [a for a in unihan.keys() if a in opencc and unihan[a] != opencc[a]]
print('Similarity:\n\tUnihan == OpenCC: {}\n\tUniHan != OpenCC: {}\n'.format(len(similar_equivalents), len(differing_equivalents)))
